# -*- coding: utf-8 -*-
"""numpy_syntecxhub

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEnQ6ICJm8g8Ikq5IjFoflmFBSfYNOBI
"""

import numpy as np

# Create 1D Array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# Create 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)

# Display attributes
print("\nShape:", arr2.shape)
print("Dimensions:", arr2.ndim)
print("Data type:", arr2.dtype)

# Indexing
print("First element of arr1:", arr1[0])
print("First row of arr2:", arr2[0])

# Slicing
print("First three elements of arr1:", arr1[:3])
print("Second column of arr2:", arr2[:, 1])

# Arithmetic operations
print("Addition:", arr1 + 2)
print("Multiplication:", arr1 * 3)

# Statistical operations
print("Mean:", np.mean(arr1))
print("Median:", np.median(arr1))
print("Standard Deviation:", np.std(arr1))

print("Sum by column:", np.sum(arr2, axis=0))
print("Sum by row:", np.sum(arr2, axis=1))

arr3 = np.arange(1, 10).reshape(3, 3)
print("Reshaped 3x3 array:\n", arr3)

# Broadcasting example
print("\nAdd 10 to every element:\n", arr3 + 10)

# Save array
np.save("my_array.npy", arr3)

# Load array
loaded = np.load("my_array.npy")
print("Loaded Array:\n", loaded)

import time

# Python list
list_data = list(range(1000000))
start = time.time()
list_result = [x * 2 for x in list_data]
end = time.time()
print("List time:", end - start)

# NumPy array
np_data = np.arange(1000000)
start = time.time()
np_result = np_data * 2
end = time.time()
print("NumPy time:", end - start)